<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitee23af1b0d350384601d1cf68335469e
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitee23af1b0d350384601d1cf68335469e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitee23af1b0d350384601d1cf68335469e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
